### ISSUE TITLE
OSError: Process terminated: Timed out

### ISSUE THREAD

**Issue by zhangxiaobai12345** [pankajb64/webfp-crawler-phantomjs#1]
I run main.py and get a 'CRITICAL - Error launching Tor'
![图片1](https://user-images.githubusercontent.com/54009924/104869248-88c17d80-5980-11eb-8763-840b2c3ba0fc.png)

**Comment by 0zhongying0** [comment]
I also encountered the same problem

**Comment by pankajb64** [comment]
Hi, thanks for trying out the crawler. I created this repo as part of a coursework, and unfortunately I don't have the time/energy to maintain this. Feel free to fork the repo and play with the code to see if it helps fix your issue.
